server:
  port: 8888

spring:
  application:
    name: config-service
  profile:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/my-project/spring-cloud-config

#        git:
#          Remote Git Repository
#          uri: https://github.com/roy-zz/spring-cloud-config.git
#          Local Git Repository
#          uri: file://${user.home}/Desktop/my-project/spring-cloud-config
#          search-paths:
#            - user
#            - order
#            - gateway
#            - catalog