server:
  port: 8888

spring:
  application:
    name: config-service
  profile:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/roy-zz/spring-cloud-config.git
          search-paths:
            - user
            - order
            - gateway
            - catalog

#        native:
#          search-locations: file://${user.home}/Desktop/my-project/spring-cloud-config
#          Local Git Repository
#          uri: file://${user.home}/Desktop/my-project/spring-cloud-config