server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    passowrd: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/roy-zz/spring-cloud-config.git
          search-paths:
            - user
            - order
            - gateway
            - catalog

management:
  endpoint:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh