server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            message: Spring Cloud Gateway GlobalFilter Message
            showPreLogger: true
            showPostLogger: true
      routes:
        - id: test-server-1
          uri: lb://TEST-SERVER-1
          predicates:
            - Path=/test-server-1/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                message: TEST-SERVER-1
                showPreLogger: true
                showPostLogger: true
        - id: test-server-2
          uri: lb://TEST-SERVER-2
          predicates:
            - Path=/test-server-2/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                message: TEST-SERVER-2
                showPreLogger: true
                showPostLogger: true