server:
  port: 8761

spring:
  application:
    name: discovery
  cloud:
    config:
      uri: http://config:8888
      name: user

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false